#!/bin/sh

# Calculate factorial
n=$1
factorial=1


# Command should take at least 1 argument
if [ $# -ne 1 ]; then
    echo "Provide only one argument"
    exit 1
fi

# Cannot find factorial of numbers less than 0
if [ $n -lt 0 ]; then
    echo "Cannot find factorial of numbers less than 0"
    exit 1
fi

# factorial of 0 or 1 is 1
if [ $n -eq 0 ] || [ $n -eq 1 ]; then
    factorial=1
else
    for i in $(seq 2 $n); do
        factorial=$((factorial * i))
    done
fi

echo "Factorial of $n is $factorial"
